import type { ParsedConfig } from '../config';
import { convertPGIdentifierToTSIdentifier } from '../shared';

interface TypeInformation {
  schema: string;
  name: string;
  isEnum: boolean;
}
/**
 * Looks up the correct TypeScript type for a given PostgreSQL type. First
 * checks the config.types object for the type, then checks whether or not the
 * type is an Enum, and if it is, creates a string that will refer to the
 * enum definition generated by IntrospeQL. If the type is not defined in
 * config.types and is not an enum, 'string' is returned.
 */
export function lookupType(
  { schema, name, isEnum }: TypeInformation,
  parentSchema: string,
  config: ParsedConfig,
) {
  const key = `${schema}.${name}`;
  if (key in config.types) {
    return config.types[key];
  }

  if (isEnum) {
    let type = `Enums.${convertPGIdentifierToTSIdentifier(name)}`;
    if (schema !== parentSchema)
      type = `${convertPGIdentifierToTSIdentifier(schema)}.${type}`;
    return type;
  }

  return 'string';
}
