import { config } from 'dotenv';
import { describe, beforeAll, beforeEach, afterEach, it, expect } from 'vitest';
import { Client } from 'pg';
import { customAlphabet } from 'nanoid';
import * as fs from 'fs/promises';
import * as path from 'path';
import { introspeql } from '../../introspeql';
import type { IntrospeQLConfig } from '../../config';

const nanoid = customAlphabet('abcdefghijklmnopqrstuvwxyz', 30);

/* 
  To run this test, be sure to create a .env file in this directory! See 
  .env.example for details.
*/
describe(
  'introspeql',
  () => {
    let dbConnectionParams: IntrospeQLConfig['dbConnectionParams'];
    let database: string;

    beforeAll(() => {
      config({ path: path.join(import.meta.dirname, '.env') });
      dbConnectionParams = {
        host: process.env.DB_HOST,
        port: +process.env.DB_PORT!,
        user: process.env.DB_USER,
        password: process.env.DB_PASSWORD,
      };
    });

    beforeEach(async () => {
      database = nanoid();
      let client = new Client(dbConnectionParams);
      await client.connect();
      await client.query(`CREATE DATABASE ${database};`);
      await client.end();

      client = new Client({
        ...dbConnectionParams,
        database,
      });

      await client.connect();
      const schema = await fs.readFile(
        path.join(import.meta.dirname, 'schema.sql'),
        'utf-8',
      );

      await client.query(schema);
      await client.end();
    });

    afterEach(async () => {
      const client = new Client(dbConnectionParams);
      await client.connect();
      await client.query(`DROP DATABASE ${database};`);
      await client.end();
    });

    it('reads data from a database and produces type definitions.', async () => {
      const config: IntrospeQLConfig = {
        schemas: ['auth', 'common', 'reporting', 'sales'],
        dbConnectionParams: {
          ...dbConnectionParams,
          database,
        },
        writeToDisk: false,
        functions: {
          mode: 'exclusive',
        },
        types: {
          ['pg_catalog.void']: 'void',
          ['pg_catalog.int8']: 'bigint',
        },
        header:
          '/* This file has been generated by IntrospeQL and should not be edited directly. */',
      };

      const expected = await fs.readFile(
        path.join(import.meta.dirname, 'expected-output.txt'),
        'utf-8',
      );

      const actual = await introspeql(config);
      expect(actual).toBe(expected);
    });
  },
  Infinity,
);
