/* This file was generated by IntrospeQL. Do not edit manually. */
/* Custom header goes here. */
export namespace Public {
  export const SchemaName = "public";

  export namespace Enums {
    export enum DistanceUnits {
      METERS = "METERS",
      KILOMETERS = "KILOMETERS",
      MILES = "MILES",
    }
  }

  export namespace Tables {
    export namespace Locations {
      export const TableName = "locations";

      export enum ColumnNames {
        Id = "id",
        Coordinates = "coordinates",
        LocationName = "location_name",
      }

      export interface RowType {
        [ColumnNames.Id]: number;
        [ColumnNames.Coordinates]: string;
        [ColumnNames.LocationName]: string | null;
      }
    }
  }

  export namespace Procedures {
    export namespace DistanceWithUnits {
      export const ProcedureName = "distance_with_units";

      export const ArgNames = ["point_a", "point_b", "units"] as const;

      export type ArgTypes = [string, string, Enums.DistanceUnits];

      export type ReturnType = number;
    }
  }
}
