import fs from "node:fs";
import type { ParsedIntrospeQLConfig } from "./introspeql-config";

export function writeHeader(
  outputPath: string,
  config: ParsedIntrospeQLConfig
) {
  const comment = `/* This file was generated by IntrospeQL. Do not edit manually. */\n`;
  const header = config.head
    ? comment + config.head + "\n".repeat(config.head.endsWith("\n") ? 1 : 2)
    : comment;

  fs.writeFileSync(outputPath, header, "utf-8");
}
